# Generated by Django 3.1 on 2020-08-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SCH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('major', models.CharField(max_length=30)),
                ('year', models.IntegerField(null=True)),
                ('studentid', models.IntegerField()),
                ('grade', models.IntegerField()),
                ('GPA', models.FloatField()),
            ],
        ),
    ]
