# Generated by Django 3.1 on 2020-08-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_sch_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='sch',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
