# Generated by Django 3.1 on 2020-08-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_sch_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sch',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
